In [1]:
%pip install pandas pyarrow

Requirement already satisfied: pandas in .\venv\Lib\site-packages (3.0.5)
Requirement already satisfied: pyarrow in .\venv\Lib\site-packages (25.0.1)
Requirement already satisfied: numpy>=1.26.0 in .\venv\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import os
from db_setup.db_connect import get_engine

In [ ]:
# Read grocery_sales from database
grocery_sales = pd.read_sql('''
                       SELECT *
                       FROM sales.grocery_sales     
                ''' , con=get_engine())

# Print head grocery_sales
print(grocery_sales.head())

   Unnamed: 0  index  Store_ID       Date  Dept  Weekly_Sales
0           0      0         1 2010-02-05     1      24924.50
1           1      1         1 2010-02-05    26      11737.12
2           2      2         1 2010-02-05    17      13223.76
3           3      3         1 2010-02-05    45         37.44
4           4      4         1 2010-02-05    28       1085.29

In [ ]:
# Assign extra_data parquet into dataframe
df_extra_data = pd.read_parquet("data/extra_data.parquet")

# Print head extra_data
df_extra_data.head()

,index,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,0,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,3.0,151315.0
1,1,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,3.0,151315.0
2,2,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,3.0,151315.0
3,3,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,NaN,3.0,151315.0
4,4,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,NaN,3.0,151315.0

In [9]:
# Extract function is already implemented for you 
def extract(store_data, extra_df):
    merged_df = store_data.merge(extra_df, on = "index")
    return merged_df

# Call the extract() function and store it as the "merged_df" variable
merged_df = extract(grocery_sales, df_extra_data)

# print head grocery_sales and info
merged_df.head()

,Unnamed: 0,index,Store_ID,Date,Dept,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,0,0,1,2010-02-05,1,24924.50,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,3.0,151315.0
1,1,1,1,2010-02-05,26,11737.12,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,3.0,151315.0
2,2,2,1,2010-02-05,17,13223.76,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,3.0,151315.0
3,3,3,1,2010-02-05,45,37.44,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,NaN,3.0,151315.0
4,4,4,1,2010-02-05,28,1085.29,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,NaN,3.0,151315.0

In [11]:
# print merged_df info
print(merged_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 231522 entries, 0 to 231521
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    231522 non-null  int64
 1   index         231522 non-null  int64
 2   Store_ID      231522 non-null  int64
 3   Date          231483 non-null  datetime64[us]
 4   Dept          231522 non-null  int64
 5   Weekly_Sales  231484 non-null  float64
 6   IsHoliday     231522 non-null  int64
 7   Temperature   231522 non-null  float64
 8   Fuel_Price    231522 non-null  float64
 9   MarkDown1     231522 non-null  float64
 10  MarkDown2     231522 non-null  float64
 11  MarkDown3     231522 non-null  float64
 12  MarkDown4     231521 non-null  float64
 13  MarkDown5     231521 non-null  float64
 14  CPI           231475 non-null  float64
 15  Unemployment  231485 non-null  float64
 16  Type          231521 non-null  float64
 17  Size          231521 non-null  float64
dtypes: datetime64[us](1), float64(12), int64(5)
memory usage: 31.8 MB
None

In [12]:
# print null data
print(merged_df.isnull().sum())

Unnamed: 0       0
index            0
Store_ID         0
Date            39
Dept             0
Weekly_Sales    38
IsHoliday        0
Temperature      0
Fuel_Price       0
MarkDown1        0
MarkDown2        0
MarkDown3        0
MarkDown4        1
MarkDown5        1
CPI             47
Unemployment    37
Type             1
Size             1
dtype: int64

In [16]:
# Check null date
print(merged_df.loc[merged_df["Date"].isna(), ["Date"]])

     Date
16    NaT
17    NaT
18    NaT
19    NaT
20    NaT
76    NaT
77    NaT
78    NaT
79    NaT
80    NaT
81    NaT
82    NaT
658   NaT
659   NaT
660   NaT
661   NaT
662   NaT
663   NaT
664   NaT
665   NaT
666   NaT
2548  NaT
2549  NaT
2550  NaT
2551  NaT
2552  NaT
2553  NaT
2554  NaT
2555  NaT
2556  NaT
3916  NaT
3917  NaT
3918  NaT
3919  NaT
3920  NaT
3921  NaT
3922  NaT
3923  NaT
3924  NaT

In [ ]:
# Check if there's a pattern for null date
print(pd.concat([
    merged_df.iloc[13:24, 3],
    merged_df.iloc[73:86, 3],
    merged_df.iloc[73:86, 3],
    merged_df.iloc[655:670, 3],
]))

13    2010-02-05
14    2010-02-05
15    2010-02-05
16           NaT
17           NaT
18           NaT
19           NaT
20           NaT
21    2010-02-05
22    2010-02-05
23    2010-02-05
73    2010-02-12
74    2010-02-12
75    2010-02-12
76           NaT
77           NaT
78           NaT
79           NaT
80           NaT
81           NaT
82           NaT
83    2010-02-12
84    2010-02-12
85    2010-02-12
73    2010-02-12
74    2010-02-12
75    2010-02-12
76           NaT
77           NaT
78           NaT
79           NaT
80           NaT
81           NaT
82           NaT
83    2010-02-12
84    2010-02-12
85    2010-02-12
655   2010-04-09
656   2010-04-09
657   2010-04-09
658          NaT
659          NaT
660          NaT
661          NaT
662          NaT
663          NaT
664          NaT
665          NaT
666          NaT
667   2010-04-09
668   2010-04-09
669   2010-04-09
Name: Date, dtype: datetime64[us]

The date null value can be filled by ffill method

In [19]:
# Percentage null in weekly_sales
print(f"{round(merged_df['Weekly_Sales'].isna().mean() * 100, 3)}%")

# Check if null based on Store_ID Dept
print(merged_df[merged_df['Weekly_Sales'].isna()]
      .groupby(['Store_ID', 'Dept'])
      .size()
      .sort_values(ascending=False))

0.016%
Store_ID  Dept
1         1       2
          6       2
          14      2
          26      2
          96      2
          87      2
          80      2
          13      1
          11      1
          21      1
          18      1
          24      1
          9       1
          8       1
          7       1
          32      1
          31      1
          27      1
          34      1
          67      1
          71      1
          41      1
          37      1
          74      1
          72      1
          83      1
          81      1
          85      1
          92      1
          94      1
          98      1
dtype: int64

In [20]:
# Check CPI & Unemployment null values
merged_df.loc[merged_df["CPI"].isna() | merged_df["Unemployment"].isna(), ["CPI", "Unemployment"]]

               CPI  Unemployment
3       211.096358           NaN
4       211.096358           NaN
5       211.096358           NaN
6       211.096358           NaN
7       211.096358           NaN
...            ...           ...
221402  134.514367           NaN
221403  134.514367           NaN
221404  134.514367           NaN
221405  134.514367           NaN
231521         NaN           NaN

[83 rows x 2 columns]

In [69]:
# Create the transform() function with one parameter: "raw_data"
def transform(raw_data):
    # Fill Date values with ffill
    raw_data["Date"] = raw_data["Date"].ffill()
    
    # Fill Weekly_Sales null values with mean
    raw_data["Weekly_Sales"] = raw_data["Weekly_Sales"].fillna(raw_data["Weekly_Sales"].mean())
    # Fill CPI null values with mean
    raw_data["CPI"] = raw_data["CPI"].fillna(raw_data["CPI"].mean())
    # FIll Unemployment null values with mean
    raw_data["Unemployment"] = raw_data["Unemployment"].fillna(raw_data["Unemployment"].mean())
    
    # Keep rows where weekly sales are over $10,000
    raw_data = raw_data.loc[raw_data["Weekly_Sales"] > 10000, :]
    
    # Add Month column
    raw_data["Month"] = raw_data["Date"].dt.month
    
    # Use necessary column
    raw_data = raw_data.loc[:, ["Store_ID", "Month", "Dept", "IsHoliday", "Weekly_Sales", "CPI", "Unemployment"]]

    return raw_data

In [70]:
# Call the transform() function and pass the merged DataFrame
clean_data = transform(merged_df)

# Print clean_data
print(clean_data.head())

   Store_ID  Month  Dept  IsHoliday  Weekly_Sales         CPI  Unemployment
0         1      2     1          0      24924.50  211.096358      8.106000
1         1      2    26          0      11737.12  211.096358      8.106000
2         1      2    17          0      13223.76  211.096358      8.106000
5         1      2    79          0      46729.77  211.096358      7.500052
6         1      2    55          0      21249.31  211.096358      7.500052

In [71]:
# Create the avg_weekly_sales_per_month function that takes in the cleaned data from the last step
def avg_weekly_sales_per_month(clean_data):
    return (clean_data.groupby("Month")
            .agg({"Weekly_Sales": 'mean'})
            .round(2)
            .reset_index()
            .rename(columns={"Weekly_Sales": "Avg_Sales"})
    )

In [72]:
# Call the avg_weekly_sales_per_month() function and pass the cleaned DataFrame
agg_data = avg_weekly_sales_per_month(clean_data)

# Print agg_data
print(agg_data)

    Month  Avg_Sales
0       1   33174.18
1       2   34331.35
2       3   33220.89
3       4   33390.86
4       5   33339.89
5       6   34582.47
6       7   33922.76
7       8   33644.79
8       9   33258.05
9      10   32731.06
10     11   36594.03
11     12   39238.80

In [73]:
# Create the load() function that takes in the cleaned DataFrame and the aggregated one with the paths where they are going to be stored
def load(full_data, full_data_file_path, agg_data, agg_data_file_path):
    full_data.to_csv(full_data_file_path, index=False)
    agg_data.to_csv(agg_data_file_path, index=False)

In [79]:
# Call the load() function and pass the cleaned and aggregated DataFrames with their paths    
clean_data_path = 'data/clean_data.csv'
agg_data_path = 'data/agg_data.csv'

load(clean_data, clean_data_path, agg_data, agg_data_path)

In [80]:
# Create the validation() function with one parameter: file_path - to check whether the previous function was correctly executed
def validation(file_path):
    exists = True
    for path in file_path:
        if os.path.exists(path) == True:
            exists = True
        else:
            exists = False
    return exists

In [81]:
# Call the validation() function and pass first, the cleaned DataFrame path, and then the aggregated DataFrame path
print(validation([clean_data_path, agg_data_path]))

True